#!/usr/bin/env bash
set -euo pipefail
[[ "${ULTRAPROMPT_DISABLE_HOOKS:-0}" == "1" ]] && exit 0

cat <<'JSON'
{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": "Ultraprompt V8.7.0 active - interactive routing picker. Catalog: 49 skills, 30 agents, 43 MCP tools, 31 commands, 12 panels, 17 artifact schemas, 2 output styles.\n\n**V8.7 adds (on top of V8.6):**\n- **Interactive routing picker.** UserPromptSubmit hook detects ambiguity (top-2 within 15% or top medium-confidence) and emits a directive instructing the model to invoke `ultraprompt:choose`. The picker skill calls `route_picker` MCP tool, generates 2 LLM-rewritten prompt variants, and surfaces 3-4 options via `AskUserQuestion` with previews. On selection, dispatches the chosen skill with the chosen phrasing.\n- New `route_picker` MCP tool: ranked candidates + previews + ambiguity metadata.\n- New `ultraprompt:choose` skill (tier=core, aliases: pick, route-interactive). Auto-invoked by the picker directive; also `/ultraprompt:choose <intent>` manually.\n- `route_picker_triggered` and `route_picker_choice` telemetry events feed the existing dashboard + learning queue.\n\n**FIRST RULE:** when uncertain how to handle a request, follow the V8.7 picker directive if one is injected (call `ultraprompt:choose` Skill) — it presents an AskUserQuestion panel for one decisive selection moment. For unambiguous prompts the silent V8.6 nudge still fires.\n\n**Dispatch defaults:**\n| Pattern | Skill / Agent |\n|---|---|\n| Whole-repo audit | `/ultraprompt:repo-review` -> `ultraprompt:repo-cartographer` |\n| Repo discovery | `/ultraprompt:repo-map` -> `ultraprompt:scout` |\n| Diff/PR review | `/ultraprompt:review` -> `ultraprompt:reviewer` |\n| Failing test/runtime bug | `/ultraprompt:debug` -> `ultraprompt:debugger` |\n| Auth/secrets/injection | `/ultraprompt:security-audit` -> `ultraprompt:security-auditor` |\n| Architecture | `/ultraprompt:architect` -> `ultraprompt:reviewer` with architecture focus |\n| Test strategy | `/ultraprompt:test-harden` -> `ultraprompt:test-strategist` |\n| New code (multi-file) | `/ultraprompt:build` -> `ultraprompt:builder` |\n| Release/docs | `/ultraprompt:release` or `/ultraprompt:docs-sync` -> `ultraprompt:writer` |\n| Red-team/critique | `/ultraprompt:panel-run adversarial` -> `ultraprompt:adversarial` |\n\n**Inline-only skills:** `refactor`, `migrate`, `llm-eval-design`, `tui-design-innovate`, `contract-test-generate`. (`build` is now dispatch-capable via `ultraprompt:builder` for multi-file scope.)\n\n**Safety:** write evidence for validation claims, use `/ultraprompt:wip-save` before risky work, and apply `${CLAUDE_PLUGIN_ROOT}/_shared/DISCIPLINE.md`."
  }
}
JSON
